### PR TITLE
adding missing nist tags and correctly formatting check and fix text …

### LINKED ISSUE #182: Some controls are missing a few metadata tags
The following controls:
SV-219059
SV-228563
SV-228564
SV-233307
SV-237633
SV-237634
SV-237635
SV-244557
SV-244558
SV-250312
SV-250313
SV-250314
SV-251702
SV-251703
SV-251704
SV-251705

Need their metadata fixed. They are missing their NIST control alignments and legacy control names, and they also need the tags for title and description etc. to be refactored as sub-descriptions in line with the rest of the controls.

### PR DESCRIPTION
**Pull request by wdower**
resolves #182

### CODE REVIEW

**Comment by wdower** [comment]
These controls were recent additions to the STIG and don't actually have legacy tags to add. I have added the NIST alignment and cleaned up the check and fix text.

File: controls/SV-228564.rb [hunk 1]
```diff
@@ -12,10 +14,9 @@
   tag fix_id: 'F-23603r419770_fix'
   tag cci: ['CCI-000162', 'CCI-000163', 'CCI-000164', 'CCI-001314']
   tag legacy: []
+  tag nist: ['AU-9']
```
Comment (karikarshivani) [inline controls/SV-228564.rb:17]: I see 'CCI-001314': `SI-11 b`

**Review by karikarshivani — APPROVED** [review]
LGTM!
