### PR TITLE
V3R10 Delta Updates

### LINKED ISSUE #145: Control metadata incorrect (all)
I noticed that the metadata for pretty much all of the controls is incorrect. At a minimum the 'severity' tag is set to 'nil' on pretty much all controls. Not sure how this happened. When I generate a new skeleton profile from the XCCDF (inspec_tools xccdf2inspec) the severity tags are set correctly.

### LINKED ISSUE #165: V-71939 - False fails due to not checking all passing configurations
In https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/master/controls/V-71939.rb, the STIG Author defines these 3 configurations as passing:

"If no line, a commented line, or a line indicating the value \"no\" is returned, the required value is set."
https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/4d1347c86a58008069f15a92ab797ad192198fb3/controls/V-71939.rb#L16-L17

However, the describe block only checks for "PermitEmptyPasswords no", which is only one of the 3 configurations allowed to pass. The other two: no line, or a commented line, should be checked to alternatively allow a pass.

### LINKED ISSUE #188: SV-204458 Profile Error for releases not covered
My target release is `7.3` which doesn't have a value assigned in the case statement. To avoid the following profile error:
Screen Shot 2023-04-14 at 3 22 42 PM

We can maybe try:
```rb
release = os.release

if !['7.6', '7.7', '7.9'].include? release
# fail
  describe "RHEL \"#{release}\" is not a supported release" do
    subject { EOMS_DATE }
    it { should_not be_nil }
    end
else
EOMS_DATE = case release
              when /^7\.6/
                '31 May 2021'
              when /^7\.7/
                '30 August 2021'
              when /^7\.9/
                '30 June 2024'
              end

  describe "The release \"#{release}\" must still be within the support window, ending #{EOMS_DATE}" do
    subject { Date.today <= Date.parse(EOMS_DATE) }
    it { should be true }
  end
end
```

### LINKED ISSUE #195: Remove redundant `expect_<input_name>` inputs
There are about 19 controls which try to validate that the input given by the user is within a bound like the following example:

```ruby
  # No files should set 'hard' 'maxlogins' to any noncompliant value
  describe 'The expected maxlogins value should be within policy limit' do
    subject { input('expected_maxlogins_limit') }
    it { should cmp <= input('max_maxlogins_limit') }
  end
```
However, doing this with 2 inputs allows the user to "grade their own homework" and increases the number of inputs and logic complexity.

Suggest:
Remove all of the `expected_<input_name>` inputs (like is done in rhel8), and remove the check (the code block above) for all relevant controls. Change the control logic to use the `<input_name>` input (e.g. `maxlogins_limit`)

### PR DESCRIPTION
**Pull request by karikarshivani**
- [x] Figure out which controls need InSpec code modifications ([shortlist](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/pull/189/commits/ba0198bb508c05962df3e408d4cde3460f90d4cf) of 84 controls)
- [x] Divide up the controls to address
- [x] Review all files changes
- [x] Compare test results from previous version and new version
- [x] Review README (especially inputs)

<details><summary>MFA</summary>
<p>

- [x] SV-204441 | Added test for `pam_pkcs_11`
- [x] SV-204631 | No logic changes. Updated language to show that the list of packages includes the dependencies
</p>
</details> 

<details><summary>grub</summary>
<p>

- [x] SV-204501
- [x] SV-244557
- [x] SV-244558

</p>
</details> 

<details><summary>cron</summary>
<p>

- [x] SV-204445
- [x] SV-204446

</p>
</details> 

<details><summary>aide</summary>
<p>

- [x] SV-204498 | Removed installation check per delta | Added input to check if conf file exists at default path
- [x] SV-204499 | Removed installation check per delta | Added input to check if conf file exists at default path
- [x] SV-204500 | Removed installation check per delta | Added input to check if conf file exists at default path
- [x] SV-251705 | Delta added initialization requirement - update InSpec code to reflect that

</p>
</details> 

<details><summary>authconfig</summary>
<p>

- [x] SV-204415 | no Inspec changes needed, all of these controls had a note updated (the wording of it was fixed)
- [x] SV-204422 | no Inspec changes needed
- [x] SV-204424  | no inspec changes needed
- [x] SV-204427 | no inspec changes needed
- [x] SV-204428 | no inspec changes needed

</p>
</details> 

<details><summary>/etc/sysctl.conf</summary>
<p>

Added to the describe block in all of the below controls to check for settings in all of the configuration files in addition to using /sbin/sysctl that is used in the resource for checking the runtime configuration.
- [x] SV-204584
- [x] SV-204609
- [x] SV-204610
- [x] SV-204611
- [x] SV-204612
- [x] SV-204613
- [x] SV-204614
- [x] SV-204615
- [x] SV-204616
- [x] SV-204617
- [x] SV-204625
- [x] SV-204630

</p>
</details> 

<details><summary>audit</summary>
<p>

- [x] SV-204517 | Delta changes don't require InSpec code changes - fix text fixed by STIG author
- [x] SV-204536 | Added 'perm=x' based on delta updates
- [x] SV-204537 | Added 'perm=x' based on delta updates
- [x] SV-204538 | Added 'perm=x' based on delta updates
- [x] SV-204539 | Added 'perm=x' based on delta updates
- [x] SV-204542 | Added 'perm=x' based on delta updates
- [x] SV-204543 | Added 'perm=x' based on delta updates
- [x] SV-204544 | Added 'perm=x' based on delta updates
- [x] SV-204545 | Added 'perm=x' based on delta updates
- [x] SV-204546 | Added 'perm=x' based on delta updates
- [x] SV-204547 | Added 'perm=x' based on delta updates
- [x] SV-204548 | Added 'perm=x' based on delta updates
- [x] SV-204550 | Added 'perm=x' based on delta updates
- [x] SV-204551 | Added 'perm=x' based on delta updates
- [x] SV-204552 | Added 'perm=x' based on delta updates
- [x] SV-204553 | Added 'perm=x' based on delta updates
- [x] SV-204554 | Added 'perm=x' based on delta updates
- [x] SV-204555 | Added 'perm=x' based on delta updates
- [x] SV-204556 | Added 'perm=x' based on delta updates
- [x] SV-204557 | Added 'perm=x' based on delta updates
- [x] SV-204558 | Added 'perm=x' based on delta updates
- [x] SV-204559 | Added other audit rule fields based on delta updates
- [x] SV-204560 | Added other audit rule fields based on delta updates
- [x] SV-204562 | Added other audit rule fields based on delta updates
- [x] SV-204563 | Added other audit rule fields based on delta updates

</p>
</details> 

<details><summary>gsettings</summary>
<p>

- [x] SV-204396 | No delta changes - Uses `gsettings` instead of `grep` so logged [issue](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/190)
- [x] SV-204398 | No delta changes - Uses `gsettings` instead of `grep`
- [x] SV-204399 | No delta changes - Uses `gsettings` instead of `grep`
- [x] SV-204400 | No delta changes - Uses `gsettings` instead of `grep`
- [x] SV-204402 | No delta changes - Uses `gsettings` instead of `grep`
- [x] SV-204403 | No delta changes - Uses `gsettings` instead of `grep`
- [x] SV-204404 | No delta changes - Uses `gsettings` instead of `grep`
- [x] SV-214937 | No delta changes - Uses `gsettings` instead of `grep`

</p>
</details> 

<details><summary>other</summary>
<p>

- [x] SV-204392 | No delta changes - `egrep` changed to `grep -E`
- [x] SV-204429 | commands have sudo in front
- [x] SV-204455  | commands have sudo in front, no inspec code changes needed
- [x] SV-204459 | please review comments | doesn't seem like inspec code changes are needed 
- [x] SV-204470 | no changes needed (it's just the example stuff that changed in this control)
- [x] SV-204479 | no changes needed
- [x] SV-204488 | removed parenthesis in find command to fix logic. Changed inv_mode to inverse_mode
- [x] SV-204504 | No logic changes. Only new caveat added for clarity.
- [x] SV-204506 | No logic changed. Only fix text clarified.
- [x] SV-204579 | Added /etc/profile.d/* to files being checked. This was already in the InSpec logic.
- [x] SV-204580 | Removed \n from NIST tag
- [x] SV-204585 | no changes needed
- [x] SV-204597 | Updated permissions from 0600 -> 0640, uses input with default value 0640, no changes needed
- [x] SV-204602 | RHEL 7.4 and above check in code - [added w/ this commit](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/commit/e0a28d036f254c98e73e5361cd61c444d5931353)
- [x] SV-237634 | Delta updated command - implemented
- [x] SV-237635 | Delta added recursive flag - implemented
- [x] SV-250314 | Delta added recursive flag - implemented
- [x] SV-251703 | Delta added a statement for NA - implemented that along with fixing the old code to test properly

</p>
</details> 

<details><summary>New controls</summary>
<p>

- [x] SV-254523 | missing Inspec logic
- [x] SV-255925 | missing Inspec logic
- [x] SV-255926 | missing Inspec logic
- [x] SV-255927 | missing Inspec logic
- [x] SV-255928 | missing Inspec logic

</p>
</details> 

<details><summary>No logic change needed because updates where negligable</summary>
<p>

- [x] SV-204397
- [x] SV-204416
- [x] SV-204417
- [x] SV-204430
- [x] SV-204432
- [x] SV-204433
- [x] SV-204434
- [x] SV-204435
- [x] SV-204444
- [x] SV-204447
- [x] SV-204448
- [x] SV-204449
- [x] SV-204450
- [x] SV-204451
- [x] SV-204452
- [x] SV-204453
- [x] SV-204454
- [x] SV-204463
- [x] SV-204464
- [x] SV-204486
- [x] SV-204497
- [x] SV-204503
- [x] SV-204507
- [x] SV-204508
- [x] SV-204509
- [x] SV-204510
- [x] SV-204511
- [x] SV-204512
- [x] SV-204513
- [x] SV-204514
- [x] SV-204515
- [x] SV-204516
- [x] SV-204531
- [x] SV-204540
- [x] SV-204541
- [x] SV-204549
- [x] SV-204564
- [x] SV-204565
- [x] SV-204566
- [x] SV-204567
- [x] SV-204568
- [x] SV-204572
- [x] SV-204575
- [x] SV-204576
- [x] SV-204577
- [x] SV-204578
- [x] SV-204581
- [x] SV-204582
- [x] SV-204583
- [x] SV-204586
- [x] SV-204587
- [x] SV-204589
- [x] SV-204591
- [x] SV-204594
- [x] SV-204595
- [x] SV-204598
- [x] SV-204599
- [x] SV-204603
- [x] SV-204605
- [x] SV-204621
- [x] SV-204632
- [x] SV-204633
- [x] SV-204634
- [x] SV-214799
- [x] SV-214800
- [x] SV-214801
- [x] SV-219059
- [x] SV-228564
- [x] SV-250312
- [x] SV-250313
- [x] SV-251704
</p>
</details> 

---

Post-merge tasks:
- [ ] Update hardening content (SV-204560 needs a key update to `modulechange`)

---

resolves #188 
resolves #145 
resolves #195 
resolves #165

### CODE REVIEW

File: controls/SV-204392.rb [hunk 1]
```diff
@@ -3,23 +3,26 @@
     and group membership of system files and commands match the vendor values.'
   desc 'Discretionary access control is weakened if a user or group has access permissions to system files and
     directories greater than the default.'
-  desc 'check', %q(Verify the file permissions, ownership, and group membership of system files and commands match the
-    vendor values.
-    Check the default file permissions, ownership, and group membership of system files and commands with the following
-    command:
-    # for i in `rpm -Va | egrep '^.{1}M|^.{5}U|^.{6}G' | cut -d " " -f 4,5`;do for j in `rpm -qf $i`;do rpm -ql $j
```
Comment (em-c-rod) [inline controls/SV-204392.rb:10]: `egrep` is the same as `grep -E`. All other changes are semantic. This control does not need updated logic.

File: controls/SV-204396.rb [hunk 2]
```diff
@@ -6,14 +6,16 @@
...
-    # grep -i lock-enabled /etc/dconf/db/local.d/*
-    lock-enabled=true
-    If the "lock-enabled" setting is missing or is not set to "true", this is a finding.)
+  desc 'check', %q(Verify the operating system enables a user's session lock until that user re-establishes access using established identification and authentication procedures.
+
+Note: If the system does not have GNOME installed, this requirement is Not Applicable.
+
+Check to see if the screen lock is enabled with the following command:
+
+     # grep -ir lock-enabled /etc/dconf/db/local.d/ | grep -v locks
```
Comment (em-c-rod) [inline controls/SV-204396.rb:15]: This update is functionally the same. However, this command in a sample rhel7 box (using Vagrant box iamseth/rhel-7.3) returns an empty string, while the InSpec command below that uses the gsettings API to get dconf settings gives the "true" response. The InSpec logic below uses the gsettings API for this check rather than checking the dconf back end directly as specified in the check text.

Should there be a describe.one that checks in both ways?

File: controls/SV-204398.rb [hunk 3]
```diff
@@ -7,13 +7,16 @@
...
-    # grep -i idle-delay /etc/dconf/db/local.d/*
-    idle-delay=uint32 900
-    If the "idle-delay" setting is missing or is not set to "900" or less, this is a finding.'
+  desc 'check', 'Verify the operating system initiates a screensaver after a 15-minute period of inactivity for graphical user interfaces.
+
+Note: If the system does not have GNOME installed, this requirement is Not Applicable.
+
+Check to see if GNOME is configured to display a screensaver after a 15 minute delay with the following command:
+
+     # grep -i idle-delay /etc/dconf/db/local.d/*
```
Comment (karikarshivani) [inline controls/SV-204398.rb:16]: Same as the `gsettings` comment. Would `describe.one` be helpful?

File: controls/SV-204399.rb [hunk 4]
```diff
@@ -7,19 +7,22 @@
...
-    path must be modified if a database other than "local" is being used.
-    # grep -i lock-delay /etc/dconf/db/local.d/locks/*
-    /org/gnome/desktop/screensaver/lock-delay
-    If the command does not return a result, this is a finding.'
+  desc 'check', 'Verify the operating system prevents a user from overriding a screensaver lock after a 15-minute period of inactivity for graphical user interfaces. 
+
+Note: If the system does not have GNOME installed, this requirement is Not Applicable.
+
+Determine which profile the system database is using with the following command:
+     # grep system-db /etc/dconf/profile/user
```
Comment (karikarshivani) [inline controls/SV-204399.rb:15]: Same as the `gsettings` comment. Would `describe.one` be helpful?

File: controls/SV-204396.rb (hunk 2 above)
Comment (karikarshivani) [reply controls/SV-204396.rb:15]: Other controls that also use `gsettings`:

- [ ] `SV-204396`
- [ ] `SV-204398`
- [ ] `SV-204399`
- [ ] `SV-204400`
- [ ] `SV-204402`
- [ ] `SV-204403`
- [ ] `SV-204404`
- [ ] `SV-204456`
- [ ] `SV-214937`

File: controls/SV-251705.rb [hunk 5]
```diff
@@ -3,28 +3,51 @@
   desc 'Without verification of the security functions, security functions may not operate correctly, and the failure may go unnoticed. Security function is defined as the hardware, software, and/or firmware of the information system responsible for enforcing the system security policy and supporting the isolation of code and data on which the protection is based. Security functionality includes, but is not limited to, establishing system accounts, configuring access authorizations (i.e., permissions, privileges), setting events to be audited, and setting intrusion detection parameters.
 
 This requirement applies to the Red Hat Enterprise Linux operating system performing security function verification/testing and/or systems and environments that require this functionality.'
-  desc 'check', 'Verify that Advanced Intrusion Detection Environment (AIDE) is installed and verifies the correct operation of all security functions.
+  desc 'check', %q(Verify that Advanced Intrusion Detection Environment (AIDE) is installed and verifies the correct operation of all security functions.
 
 Check that the AIDE package is installed with the following command:
+     $ sudo rpm -q aide
```
Comment (karikarshivani) [inline controls/SV-251705.rb:9]: Check text hasn't changed, Fix text has changed to ensure that initialization and verification steps are followed in addition to the installation of `aide`. I'd like to propose the following code after updating the default value for `file_integrity_tool` input to be an empty string:
```rb
  describe.one do
    describe package('aide') do
      it { should be_installed }
    end
    describe package(input('file_integrity_tool')) do
      it { should be_installed }
    end
  end
```

File: controls/SV-251703.rb [hunk 6]
```diff
@@ -25,11 +27,12 @@
 Add or modify the following line:
 #includedir /etc/sudoers.d'
   impact 0.5
+  ref 'DPMS Target Red Hat Enterprise Linux 7'
   tag severity: 'medium'
   tag gtitle: 'SRG-OS-000480-GPOS-00227'
-  tag satisfies: nil
+  tag 'satisfies'
```
Comment (karikarshivani) [inline controls/SV-251703.rb:33]: Should I manually revert this to the nil value to retain the original code? @em-c-rod

File: controls/SV-204631.rb [hunk 7]
```diff
@@ -19,20 +19,19 @@
...
-  desc 'fix', 'Configure the operating system to implement multifactor authentication by
-installing the required packages.
+  desc 'fix', 'Configure the operating system to implement multifactor authentication by installing the required packages.
 
-Install the "esc" and "pam_pkcs11" packages on the system with the
-following command:
+Install the pam_pkcs11 package with the following command:
 
-# yum install esc pam_pkcs11'
+# yum install pam_pkcs11'
```
Comment (karikarshivani) [inline controls/SV-204631.rb:26]: V3R6 required `esc` and `pam_pkcs11` and V3R10 requires only `pam_pkcs11`. Not sure why all of these packages are set as a default requirement for MFA:
```yml
  # V-204631
  - name: mfa_pkg_list
    description: The list of packages needed for MFA on RHEL
    type: Array
    value:
      - "nss-tools"
      - "nss-pam-ldapd"
      - "esc"
      - "pam_pkcs11"
      - "pam_krb5"
      - "opensc"
      - "pcsc-lite-ccid"
      - "gdm"
      - "authconfig"
      - "authconfig-gtk"
      - "krb5-libs"
      - "krb5-workstation"
      - "krb5-pkinit"
      - "pcsc-lite"
      - "pcsc-lite-libs"
```

Also, should the following code block be a conditional fail (instead of a skip) if multifactor authentication packages are not installed?
```rb
if smart_card_status.eql?('disabled')
      impact 0.5
      describe 'The system is not smartcard enabled thus this control is Not Applicable' do
        skip 'The system is not using Smartcards / PIVs to fulfil the MFA requirement, this control is Not Applicable.'
      end
```

I can think of one scenario where it could be a skip:
```rb
# pseudocode
if smart_card_status.eql?('disabled')
  describe package('pam_pkcs11') do
    it { should be_installed }
  end
else
  impact 0.0
  describe 'Manually review and verify that hardware MFA solutions are used as stated in the inputs' do
    skip 'Manually review and verify that Smart Cards/ PIVs/ CACs/ Tokens are used as stated in the inputs'
  end
end
```

File: controls/SV-204415.rb [hunk 8]
```diff
@@ -14,20 +14,23 @@
...
-    Note: Manual changes to the listed files may be overwritten by the "authconfig" program. The "authconfig" program
-    should not be used to update the configurations listed in this requirement.'
+
+Add the following line in "/etc/pam.d/system-auth":
+     pam_unix.so sha512 shadow try_first_pass use_authtok
+
+Add the following line in "/etc/pam.d/password-auth":
+     pam_unix.so sha512 shadow try_first_pass use_authtok
+
+Note: Per requirement RHEL-07-010199, RHEL 7 must be configured to not overwrite custom authentication configuration settings while using the authconfig utility, otherwise manual changes to the listed files will be overwritten whenever the authconfig utility is used.'
```
Comment (em-c-rod) [inline controls/SV-204415.rb:24]: Only updating the fix text. The check text is the same and the describe logic can remain as is.

File: controls/SV-255928.rb [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+  tag severity: 'medium'
+  tag gid: 'V-255928'
+  tag rid: 'SV-255928r880830_rule'
+  tag stig_id: 'RHEL-07-010199'
+  tag gtitle: 'SRG-OS-000073-GPOS-00041'
+  tag fix_id: 'F-59548r880829_fix'
+  tag 'documentable'
+  tag cci: ['CCI-000196']
+  tag nist: ['IA-5 (1) (c)']
+end
```
Comment (karikarshivani) [inline controls/SV-255928.rb:86]: Remember to review these controls simultaneously for alignment:

- [ ] SV-204415
- [ ] SV-204422
- [ ] SV-204424
- [ ] SV-204427
- [ ] SV-204428

File: controls/SV-204415.rb (hunk 8 above)
Comment (karikarshivani) [reply controls/SV-204415.rb:24]: Discussed on a group call with Eugene to determine that no changes are required for these controls as the check text is the same and the "authconfig" note was set as a separate requirement as [mentioned in this comment](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/pull/189/files#r1170293635).

File: controls/SV-204396.rb (hunk 2 above)
Comment (karikarshivani) [reply controls/SV-204396.rb:15]: Established that this is a baseline issue and not a delta issue so [logged it](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/190) to address later.

File: controls/SV-204580.rb [hunk 10]
```diff
@@ -82,7 +83,7 @@
   tag stig_id: 'RHEL-07-040170'
   tag fix_id: 'F-4704r297486_fix'
   tag cci: ['CCI-000048', 'CCI-000050', 'CCI-001384', 'CCI-001385', 'CCI-001386', 'CCI-001387', 'CCI-001388']
-  tag nist: ['AC-8 a', 'AC-8 b', 'AC-8 c 1', 'AC-8 c 2', 'AC-8 c 2', 'AC-8 c\n2', 'AC-8 c 3']
+  tag nist: ['AC-8 a', 'AC-8 b', 'AC-8 c 1', 'AC-8 c 2', 'AC-8 c\\n2', 'AC-8 c 3']
```
Comment (ssayed118) [inline controls/SV-204580.rb:86]: There's a \n in here btw

File: controls/SV-251705.rb (hunk 5 above)
Comment (karikarshivani) [reply controls/SV-251705.rb:9]: Updated code after working with Eugene with https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/pull/189/commits/793ce63f1f4d3d45a889efe8a2b1360b167fd344

Decided to not use the following way of testing initialization because users could circumvent it:
```rb
describe "File integrity tool 'aide' should be initialized" do
  subject { file('/var/lib/aide/aide.db.gz').exist? }
  it { should be true }
end
```

File: controls/SV-204445.rb [hunk 11]
```diff
@@ -1,43 +1,40 @@
...
-    application does not exist, this is a finding.'
-  desc 'fix', 'Configure the file integrity tool to run automatically on the system at least weekly. The following
-    example output is generic. It will set cron to run AIDE daily, but other file integrity tools may be used:
-    # more /etc/cron.daily/aide
-    #!/bin/bash
-    /usr/sbin/aide --check | /bin/mail -s "$HOSTNAME - Daily aide integrity check run" root@sysname.mil'
+
+Note: A file integrity tool other than Advanced Intrusion Detection Environment (AIDE) may be used, but the tool must be executed at least once per week.
+
+Check for the presence of a cron job running daily or weekly on the system that executes AIDE daily to scan for changes to the system baseline. The command used in the example will use a daily occurrence.
```
Comment (karikarshivani) [inline controls/SV-204445.rb:11]: Monthly jobs should not pass the test. The rule says it should be at least weekly, so a monthly interval should fail by default. 
The new release removed the requirement of checking if `aide` is installed (since that's already done in SV-251705. So we could follow the same approach we did in that control's modification - test if `aide` is the file integrity tool or skip to review manually.

Another approach is to assume the default cron job paths and run the tests with the input.

File: controls/SV-204429.rb [hunk 12]
```diff
@@ -6,27 +6,33 @@
...
-    # grep -i nopasswd /etc/sudoers.d/*
-    Remove any occurrences of "NOPASSWD" tags in the file.'
+
+Check the configuration of the "/etc/sudoers" file with the following command:
+$ sudo visudo
+
+Remove any occurrences of "NOPASSWD" tags in the file.
+
+Check the configuration of the /etc/sudoers.d/* files with the following command:
+$ sudo grep -ir nopasswd /etc/sudoers.d
```
Comment (em-c-rod) [inline controls/SV-204429.rb:23]: The changes add sudo to this command. The InSpec logic can remain the same.

File: controls/SV-204631.rb (hunk 7 above)
Comment (karikarshivani) [reply controls/SV-204631.rb:26]: Other controls impacted by similar logic:

- [ ] SV-204441

File: controls/SV-204446.rb [hunk 13]
```diff
@@ -1,50 +1,48 @@
...
-    side effects, some of which may be relevant to security.
-    Detecting such changes and providing an automated response can help avoid unintended, negative consequences that
-    could ultimately affect the security state of the operating system. The operating system's Information Management
-    Officer (IMO)/Information System Security Officer (ISSO) and System Administrators (SAs) must be notified via email
-    and/or monitoring system trap when there is an unauthorized modification of a configuration item."
-  desc 'check', 'Verify the operating system notifies designated personnel if baseline configurations are changed in
-    an unauthorized manner.
-    Note: A file integrity tool other than Advanced Intrusion Detection Environment (AIDE) may be used, but the tool
-    must be executed and notify specified individuals via email or an alert.
-    Check to see if AIDE is installed on the system with the following command:
```
Comment (em-c-rod) [inline controls/SV-204446.rb:15]: Update this control's logic in the same pattern as SV-204445

File: controls/SV-204455.rb [hunk 14]
```diff
@@ -7,24 +7,32 @@
...
-  desc 'fix', 'Configure the system to disable the Ctrl-Alt-Delete sequence for the command line with the following
-    command:
-    # systemctl mask ctrl-alt-del.target'
+
+Check that the ctrl-alt-del.target is masked and not active with the following command:
+
+$ sudo systemctl status ctrl-alt-del.target
+
+ctrl-alt-del.target
+Loaded: masked (/dev/null; bad)
```
Comment (em-c-rod) [inline controls/SV-204455.rb:16]: The InSpec code does not check for the value to be masked. When testing locally, the InSpec test passed when the the system's response to the command was:
```
Loaded: loaded (/usr/lib/systemd/system/reboot.target: disabled: vendor present: disabled)
Actice: inactive (dead)
```

and when the response was:
```
Loaded: masked (/dev/null: bad)
Active: inactive (dead)
```

Comment (karikarshivani) [reply controls/SV-204455.rb:16]: Proposed code:
```rb
service_status = systemd_service('ctrl-alt-del.target').params

describe service_status do
  its('LoadState') { should cmp 'masked' }
  its('ActiveState') { should cmp 'inactive' }
end
```

Need to run it by Aaron to understand the HashieMash output

File: controls/SV-254523.rb
Comment (ssayed118) [inline controls/SV-254523.rb:1]: These controls have no InSpec code:
SV-254523
SV-255925
SV-255926
SV-255927
SV-255928

File: controls/SV-204470.rb [hunk 15]
```diff
@@ -4,29 +4,33 @@
...
+
+Check the home directory assignment for all local interactive users on the system with the following command:
+
+     # ls -ld $(awk -F: '($3>=1000)&&($7 !~ /nologin/){print $6}' /etc/passwd)
+     -rwxr-x--- 1 smithj users 13 Apr 1 04:20 /home/smithj
+
+Check the user's primary group with the following command:
+
+     # grep $(grep smithj /etc/passwd | awk -F: '{print $4}') /etc/group
+     users:x:250:smithj,marinc,chongt
```
Comment (em-c-rod) [inline controls/SV-204470.rb:17]: This is just changing the example names, not logic.

File: controls/SV-204479.rb [hunk 16]
```diff
@@ -3,16 +3,19 @@
...
-    List all device files on the system that are incorrectly labeled with the following commands:
-    Note: Device files are normally found under "/dev", but applications may place device files in other directories and
-    may necessitate a search of the entire system.
-    #find /dev -context *:device_t:* \( -type c -o -type b \) -printf "%p %Z\n"
-    #find /dev -context *:unlabeled_t:* \( -type c -o -type b \) -printf "%p %Z\n"
-    Note: There are device files, such as "/dev/vmci", that are used when the operating system is a host virtual
-    machine. They will not be owned by a user on the system and require the "device_t" label to operate. These device
-    files are not a finding.
-    If there is output from either of these commands, other than already noted, this is a finding.)
+  desc 'check', 'Verify that all system device files are correctly labeled to prevent unauthorized modification.
```
Comment (em-c-rod) [inline controls/SV-204479.rb]: Only quotation changes. Changed back to using %q()

File: controls/SV-204459.rb [hunk 17]
```diff
@@ -8,41 +8,31 @@
     exist, patches are usually made available by the vendor to resolve the problems. If the most recent security patches
     and updates are not installed, unauthorized users may take advantage of weaknesses in the unpatched software. The
     lack of prompt attention to patching could result in a system compromise.'
-  desc 'check', 'Verify the operating system security patches and updates are installed and
-      up to date. Updates are required to be applied with a frequency determined by
-      the site or Program Management Office (PMO).
+  desc 'check', 'Verify the operating system security patches and updates are installed and up to date. Updates are required to be applied with a frequency determined by the site or Program Management Office (PMO).
```
Comment (em-c-rod) [inline controls/SV-204459.rb:11]: Should the InSpec code be checking for updates at a particular frequency?

File: controls/SV-204459.rb [hunk 18]
```diff
@@ -8,41 +8,31 @@
...
-      the system with the following command:
+Check that the available package security updates have been installed on the system with the following command:
 
-          # yum history list | more
-          Loaded plugins: langpacks, product-id, subscription-manager
-          ID     | Command line             | Date and time    | Action(s)      |
-      Altered
+# yum history list | more
+Loaded plugins: langpacks, product-id, subscription-manager
+ID     | Command line             | Date and time    | Action(s)      | Altered
```
Comment (em-c-rod) [inline controls/SV-204459.rb:19]: This was not the table contents that showed up when testing on a local instance.

Actual Results:
```
inspec> command('yum history list').stdout.split("\n")
=> ["Loaded plugins: langpacks, product-id, search-disabled-repos",
 "ID     | Login user               | Date and time    | Action(s)      | Altered",
 "-------------------------------------------------------------------------------",
 "     8 |  <vagrant>               | 2016-12-21 00:37 | Install        |    6  <",
 "     7 |  <vagrant>               | 2016-12-20 22:20 | Install        |   16 > ",
 "     6 |  <vagrant>               | 2016-12-20 22:19 | Install        |    3   ",
 "     5 |  <vagrant>               | 2016-12-20 22:17 | Install        |    4   ",
 "     4 |  <vagrant>               | 2016-12-20 19:36 | Erase          |    2   ",
 "     3 |  <vagrant>               | 2016-12-20 19:34 | Install        |   30   ",
 "     2 |  <vagrant>               | 2016-12-20 19:29 | I, U           |  306 EE",
 "     1 | System <unset>           | 2016-04-20 19:30 | Install        |  507   ",
 "history list"]
 ```

File: controls/SV-251703.rb [hunk 19]
```diff
@@ -3,7 +3,9 @@
...
 
 It is possible to include other sudoers files from within the sudoers file currently being parsed using the #include and #includedir directives. When sudo reaches this line it will suspend processing of the current file (/etc/sudoers) and switch to the specified file/directory. Once the end of the included file(s) is reached, the rest of /etc/sudoers will be processed. Files that are included may themselves include other files. A hard limit of 128 nested include files is enforced to prevent include file loops.'
-  desc 'check', 'Verify the operating system specifies only the default "include" directory for the /etc/sudoers file with the following command:
+  desc 'check', 'Note: If the "include" and "includedir" directives are not present in the /etc/sudoers file, this requirement is not applicable.
+
```
Comment (karikarshivani) [inline controls/SV-251703.rb:7]: Delta update: Add a condition to set requirement to NA if `include` or `includedir` are not present in the /etc/sudoers file.

Existing logic flaw: regex wasn't returning `#includedir` that was present. And grep for /etc/sudoers.d was a recursive search.

Proposed code:
```rb
if command('grep include /etc/sudoers').stdout.empty?
  impact 0.0
  describe 'This requirement is not applicable as "include" and "includedir" directives are not present in the /etc/sudoers file' do
    skip 'This requirement is not applicable as "include" and "includedir" directives are not present in the /etc/sudoers file'
  end
elsif virtualization.system.eql?('docker') && !command('sudo').exist?
  impact 0.0
  describe 'Control not applicable within a container without sudo enabled' do
    skip 'Control not applicable within a container without sudo enabled'
  end
else
  describe 'Only the default "include" directory for /etc/sudoers file should be specified' do
    subject { command('grep include /etc/sudoers').stdout.strip }
    it { should cmp "#includedir /etc/sudoers.d"}
  end
  describe 'Nested "include" files or directories within /etc/sudoers.d directory should not exist' do
    subject { command('grep -r include /etc/sudoers.d').stdout }
    it { should be_empty }
  end
end
```

File: controls/SV-250314.rb [hunk 20]
```diff
@@ -40,7 +42,7 @@
       skip 'Control not applicable within a container -- kernel config'
     end
   else
-    describe command('grep sysadm_r /etc/sudoers /etc/sudoers.d/*').stdout.strip do
+    describe command('grep -r sysadm_r /etc/sudoers /etc/sudoers.d').stdout.strip do
       it { should match /TYPE=sysadm_t\s+ROLE=sysadm_r/ }
```
Comment (karikarshivani) [inline controls/SV-250314.rb:46]: Not sure if we need to match the entire output from the check text: `%wheel ALL=(ALL) TYPE=sysadm_t ROLE=sysadm_r ALL`

File: controls/SV-251703.rb (hunk 19 above)
Comment (karikarshivani) [reply controls/SV-251703.rb:7]: After discussing with @ejaronne, updated the matcher to match and allowed for several spaces

File: controls/SV-204602.rb [hunk 21]
```diff
@@ -32,6 +37,13 @@
     describe 'Control not applicable - SSH is not installed within containerized RHEL' do
       skip 'Control not applicable - SSH is not installed within containerized RHEL'
     end
+
```
Comment (ssayed118) [inline controls/SV-204602.rb:40]: Not tested yet

File: controls/SV-204631.rb (hunk 7 above)
Comment (karikarshivani) [reply controls/SV-204631.rb:26]: After discussing with @aaronlippold, we decided to add verbiage about the dependencies for `pam_pkcs11`

File: controls/SV-204580.rb (hunk 10 above)
Comment (karikarshivani) [reply controls/SV-204580.rb]: Removed it - thanks!

File: controls/SV-204597.rb [hunk 22]
```diff
@@ -1,25 +1,28 @@
 control 'SV-204597' do
-  title 'The Red Hat Enterprise Linux operating system must be configured so that the SSH private host key files
-    have mode 0600 or less permissive.'
+  title 'The Red Hat Enterprise Linux operating system must be configured so that the SSH private host key files have mode 0640 or less permissive.'
```
Comment (karikarshivani) [inline controls/SV-204597.rb:2]:
```yml
  # SV-204597
  - name: private_host_key_file_mode
    description: Maximum mode allowed for directories containing SSH private host keys (in octal format)
    type: String
    value: "0640"
```

Why are we providing an option to the users to modify this value? This could lead to non-compliance.

File: controls/SV-204488.rb [hunk 23]
```diff
@@ -67,7 +71,7 @@
 
       if is_local == 0
         # Get user's initialization files
-        dotfiles += command("find #{u.home} -xdev -maxdepth 2 ( -name '.*' ! -name '.bash_history' ) -type f").stdout.split("\n")
```
Comment (karikarshivani) [inline controls/SV-204488.rb:70]: Context behind removing parentheses:

Screen Shot 2023-04-26 at 10 07 02 AM

File: controls/SV-204488.rb [hunk 24]
```diff
@@ -22,11 +26,11 @@
   tag severity: 'medium'
   tag gtitle: 'SRG-OS-000480-GPOS-00227'
   tag gid: 'V-204488'
-  tag rid: 'SV-204488r603261_rule'
+  tag rid: 'SV-204488r861006_rule'
   tag stig_id: 'RHEL-07-021040'
   tag fix_id: 'F-4612r88657_fix'
   tag cci: ['CCI-000318', 'CCI-000368', 'CCI-001812', 'CCI-001813', 'CCI-001814']
-  tag nist: ['CM-3 f', 'CM-6 c', 'CM-11 (2)', 'CM-5 (1)', 'CM-5 (1)']
+  tag nist: ['CM-3 f', 'CM-6 c', 'CM-11 (2)', 'CM-5 (1)', 'CM-5 (1) (a)']
```
Comment (em-c-rod) [inline controls/SV-204488.rb:33]: Comment for unchanged code below:

Rename variable `inv_mode` to describe the purpose of this variable. What is the purpose?

File: controls/SV-250314.rb (hunk 20 above)
Comment (ejaronne) [reply controls/SV-250314.rb:46]: I'd just leave it be, because in theory there can be aliases and other ways of identifying users or groups of users to have admin rights other than using the wheel group.

**Review by ejaronne — CHANGES_REQUESTED** [review]

File: controls/SV-204584.rb [hunk 25]
```diff
@@ -45,7 +45,22 @@
...
+    results_in_files.each do |result|
+      values.append(parse_config(result).params.values)
+    end
 
+    unique_values = values.uniq.flatten
+    describe 'kernel.randomize_va_space' do
+      it "should be set to #{randomize_va_space} in the configuration files" do
+        expect(unique_values.length).to be_in [0, 1]
+        if(unique_values.length > 0)
+          expect(unique_values[0]).to cmp randomize_va_space
```
Comment (em-c-rod) [inline controls/SV-204584.rb:60]: @karikarshivani What's the best way to write out these describe blocks?

File: controls/SV-204428.rb [hunk 26]
```diff
@@ -17,25 +17,25 @@
     account required pam_faillock.so
     If the "even_deny_root" setting is not defined on both lines with the "pam_faillock.so" module, is commented out, or
```
Comment (karikarshivani) [inline controls/SV-204428.rb:18]: Since the `even_deny_root` setting needs to be present on **both** lines, I think we need to remove `describe.one` and just have two `its` statements. Also, should we be adding more to the expected pam rule to:

> Verify the operating system automatically locks the root account, for a minimum of 15 minutes, when
    three unsuccessful logon attempts in 15 minutes are made.

File: controls/SV-204488.rb (hunk 24 above)
Comment (karikarshivani) [reply controls/SV-204488.rb:33]: Renamed the variable name after talking to Aaron

File: controls/SV-204455.rb (hunk 14 above)
Comment (karikarshivani) [reply controls/SV-204455.rb:16]: Split into two describe blocks to avoid the HashieMash output and keep it simple

File: controls/SV-250314.rb (hunk 20 above)
Comment (karikarshivani) [reply controls/SV-250314.rb:46]: The expected regex is left the way it was. Thanks!

File: controls/SV-204631.rb (hunk 7 above)
Comment (karikarshivani) [reply controls/SV-204631.rb:26]: Verbiage added and no other changes needed

File: controls/SV-255928.rb (hunk 9 above)
Comment (karikarshivani) [reply controls/SV-255928.rb:85]: `describe.one` should not be there because both files require pam rules

**Comment by ejaronne** [comment]
(pre-existing condition in main) - when I run this, I get the error on the command line:
WARN: Input 'x11-enabled' does not have a value. Use --input-file or --input to provide a value for 'x11-enabled' or specify a  value with `input('x11-enabled', value: 'somevalue', ...)`.

https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/6f9578499503945f9946dd254c83c70eeb99e5a4/controls/SV-204624.rb#L41 refers to X11-enabled, 

But the inspec.yml defines X11_enabled. Need to be consistent.

File: controls/SV-255928.rb (hunk 9 above)
Comment (karikarshivani) [reply controls/SV-255928.rb:85]: Need to discuss how to handle `include` rule checks

File: controls/SV-204445.rb (hunk 11 above)
Comment (karikarshivani) [reply controls/SV-204445.rb:11]: Need to log it as an issue

File: controls/SV-204441.rb [hunk 27]
```diff
@@ -12,16 +12,21 @@
...
+
+If no results are returned, this is a finding.
+
+# authconfig --test | grep "smartcard removal action"
+
+If "smartcard removal action" is blank, this is a finding.
+
+# authconfig --test | grep "smartcard module"
+
+If any of the above checks are not configured, ask the administrator to indicate the AO-approved multifactor authentication in use and the configuration to support it. If there is no evidence of multifactor authentication, this is a finding.'
```
[the remark this answers is not in the document]
Comment (karikarshivani) [reply controls/SV-204441.rb:29]: Log an issue to turn skip into manual review (use check text `AO-approved` language)

File: controls/SV-204602.rb (hunk 21 above)
Comment (karikarshivani) [reply controls/SV-204602.rb:40]: Tested it and it works but need to log an issue for SV-204588 that doesn't have the `7.4` release condition

File: controls/SV-204584.rb (hunk 25 above)
Comment (karikarshivani) [reply controls/SV-204584.rb]: We finalized an approach

File: controls/SV-204428.rb (hunk 26 above)
Comment (karikarshivani) [reply controls/SV-204428.rb:18]: Removed `describe.one`

File: controls/SV-204603.rb [hunk 28]
```diff
@@ -45,7 +45,7 @@
   tag gtitle: 'SRG-OS-000355-GPOS-00143'
   tag satisfies: ['SRG-OS-000355-GPOS-00143', 'SRG-OS-000356-GPOS-00144']
   tag gid: 'V-204603'
```
Comment (karikarshivani) [inline controls/SV-204603.rb:47]: Need to log an issue to avoid inspec exec error:
```
[2023-05-10T12:08:18-04:00] WARN: Input 'max_poll' does not have a value. Use --input-file or --input to provide a value for 'max_poll' or specify a  value with `input('max_poll', value: 'somevalue', ...)`.
[2023-05-10T12:08:18-04:00] WARN: Input 'max_poll' does not have a value. Use --input-file or --input to provide a value for 'max_poll' or specify a  value with `input('max_poll', value: 'somevalue', ...)`.
```
Although the default value is accessible and it shows in the report, this output can be avoided by assigning the input value to a variable within the control.

File: controls/SV-255928.rb (hunk 9 above)
Comment (karikarshivani) [reply controls/SV-255928.rb:128]: Used `parse_config_file` to perform checks instead

File: controls/SV-204445.rb (hunk 11 above)
Comment (karikarshivani) [reply controls/SV-204445.rb:11]: Logged issue #192

File: controls/SV-204441.rb (hunk 27 above)
[the remark this answers is not in the document]
Comment (karikarshivani) [reply controls/SV-204441.rb:29]: Logged issue #193

File: controls/SV-204602.rb (hunk 21 above)
Comment (karikarshivani) [reply controls/SV-204602.rb:40]: Added the missing condition for SV-204588 https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/pull/189/commits/17d8bc5f9ce482d6a0184a423ff55c9a84dc91c0

File: controls/SV-204603.rb (hunk 28 above)
Comment (karikarshivani) [reply controls/SV-204603.rb:47]: Logged issue #194

**Review by Amndeep7 — CHANGES_REQUESTED** [review]
https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/V3R10/spec/.DS_Store

probably wanna do a pass through to make sure that you don’t have random dotfiles in the repo

and then update your gitignore

**Review by Amndeep7 — CHANGES_REQUESTED** [review]
As we go through and update the hardening content to match the updated validation content, can we verify that the vanilla role is doing what it needs to do?  Seems like it's installing a few applications for no apparent reason.

File: libraries/pam.rb
Comment (Amndeep7) [inline libraries/pam.rb:1]: the comment on line 4 says that the two attributes there are aliases for one another.  ruby contains the alias keyword to explicitly define that relationship.  unfortunately it doesn't seem possible to alias attributes directly, but it is possible to alias their setter/getter methods (we only need the getter method aliased since we're using attr_reader).  https://stackoverflow.com/a/913359/645647

imo we should do this that instead of relying on a comment to explain this relationship.  example:

```
irb(main):060:1* class Test
irb(main):061:1*   attr_reader :a, :b
irb(main):062:1*   alias :b :a # read as 'overwrite the getter function for b with the getter function for a'
irb(main):063:2*   def initialize
irb(main):064:2*     @a = 5
irb(main):065:1*   end
irb(main):066:0> end
=> :initialize
irb(main):067:0> t = Test.new
=> #<Test:0x00007fe235928690 @a=5>
irb(main):068:0> t.a
=> 5
irb(main):069:0> t.b
=> 5
```

**Review by Amndeep7 — CHANGES_REQUESTED** [review]

**Review by Amndeep7 — CHANGES_REQUESTED** [review]
Address the todo: https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/V3R10/libraries/matchers.rb#L3

File: controls/SV-204415.rb [hunk 29]
```diff
@@ -15,33 +14,34 @@
...
-  describe.one do
-    describe pam('/etc/pam.d/password-auth') do
-      its('lines') { should match_pam_rule('password sufficient pam_unix.so sha512') }
-      its('lines') { should_not match_pam_rule('password .* pam_unix.so (md5|bigcrypt|sha256|blowfish)') }
-    end
-    describe pam('/etc/pam.d/system-auth') do
-      its('lines') { should match_pam_rule('password sufficient pam_unix.so sha512') }
-      its('lines') { should_not match_pam_rule('password .* pam_unix.so (md5|bigcrypt|sha256|blowfish)') }
-    end
+  describe pam('/etc/pam.d/password-auth') do
```
Comment (Amndeep7) [inline controls/SV-204415.rb:39]: ideally 'PAM Config[/etc/pam.d/system-auth] lines is expected to include password sufficient pam_unix.so sha512' is turned into something like "PAM Config[/etc/pam.d/system-auth] is expected to include the rule 'password sufficient pam+unix.so sha512'".

i think mentioning the 'lines' attribute is a needless display of the internals of a utility we placed in the pam resource.  all the user cares is if the rule exists or not.

File: controls/SV-204416.rb [hunk 30]
```diff
@@ -16,17 +15,18 @@
...
+  tag fix_id: 'F-4540r88441_fix'
+  tag cci: ['CCI-000196']
   tag nist: ['IA-5 (1) (c)']
-  tag subsystems: ["login_defs","password"]
-  tag 'host', 'container'
+  tag subsystems: ['login_defs', 'password']
+  tag 'host'
+  tag 'container'
 
   describe login_defs do
```
Comment (Amndeep7) [inline controls/SV-204416.rb:31]: 'login.defs ENCRYPT_METHOD is expected to cmp == "SHA512"'

maybe we can put login_defs as the subject and make it more clear what the test is expecting like

```
describe 'The "ENCRYPT_METHOD" configuration setting in /etc/login.defs should be "SHA512"' do
  subject login_defs
  blah
end
```

Comment (Amndeep7) [reply controls/SV-204416.rb:31]: I think we should more consistently provide human readable/actionable output throughout all of these controls.

File: controls/SV-204417.rb [hunk 31]
```diff
@@ -17,17 +16,18 @@
...
+  tag fix_id: 'F-4541r88444_fix'
+  tag cci: ['CCI-000196']
   tag nist: ['IA-5 (1) (c)']
-  tag subsystems: ["libuser_conf","password"]
-  tag 'host', 'container'
+  tag subsystems: ['libuser_conf', 'password']
+  tag 'host'
+  tag 'container'
 
   describe command('cat /etc/libuser.conf | grep -i sha512') do
```
Comment (Amndeep7) [inline controls/SV-204417.rb:32]: this should probably be a resource.

**Review by Amndeep7 — CHANGES_REQUESTED** [review]

File: controls/SV-204438.rb [hunk 32]
```diff
@@ -19,41 +18,39 @@
...
+  tag rid: 'SV-204438r744095_rule'
+  tag stig_id: 'RHEL-07-010482'
+  tag fix_id: 'F-4562r744094_fix'
+  tag cci: ['CCI-000213']
   tag nist: ['AC-3']
-  tag subsystems: ["boot","bios"]
+  tag subsystems: ['boot', 'bios']
   tag 'host'
 
   if virtualization.system.eql?('docker')
```
Comment (Amndeep7) [inline controls/SV-204438.rb:33]: image

idk if there is a 'virtualization.system' for determining if it's an ec2 box.  fairly sure the box i spun up is more or less a vm as opposed to anything raw metal.

regardless, we should probably have an explicit check if the file is there and make a fail/skip decision accordingly as opposed to letting it skip out like this unintentionally.

for your debugging purposes, this happened on both of the following AMIs running on t2.micros using the default ec2.inputs.yml that's bundled in the repo.

https://aws.amazon.com/marketplace/pp/prodview-4rvgwodhco57y?sr=0-1&ref_=beagle&applicationId=AWSMPContessa

https://aws.amazon.com/marketplace/pp/prodview-5ydzzv4pbudbm?sr=0-7&ref_=beagle&applicationId=AWSMPContessa

File: controls/SV-204440.rb [hunk 33]
```diff
@@ -19,48 +18,46 @@
...
+  tag rid: 'SV-204440r744098_rule'
+  tag stig_id: 'RHEL-07-010491'
+  tag fix_id: 'F-4564r744097_fix'
+  tag cci: ['CCI-000213']
   tag nist: ['AC-3']
-  tag subsystems: ["boot", "uefi"]
+  tag subsystems: ['boot', 'uefi']
   tag 'host'
 
   if virtualization.system.eql?('docker')
```
Comment (Amndeep7) [inline controls/SV-204440.rb:33]: similar to 204438, we might be skipping out via the bios claim incorrectly.  https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/virtualization_types.html.  but then again the management console page for the ec2 instances says both of them were `Current instance boot mode: legacy-bios` so idk lol.  i don't know enough about how aws does stuff.

File: controls/SV-204444.rb [hunk 34]
```diff
@@ -39,22 +38,22 @@
...
   tag 'host'
 
   if virtualization.system.eql?('docker')
     impact 0.0
-    describe "Control not applicable - SELinux settings must be handled on host" do
-      skip "Control not applicable - SELinux settings must be handled on host"
+    describe 'Control not applicable - SELinux settings must be handled on host' do
+      skip 'Control not applicable - SELinux settings must be handled on host'
     end
   else
```
Comment (Amndeep7) [inline controls/SV-204444.rb:59]: might just be cause it's late, but idk what especially that last one wants from me.  think the language for the other 3 is parsable but could be clearer

image

File: controls/SV-204445.rb [hunk 35]
```diff
@@ -1,57 +1,56 @@
...
   file_integrity_tool = input('file_integrity_tool')
   file_integrity_interval = input('file_integrity_interval')
 
-  describe package(file_integrity_tool) do
-    it { should be_installed }
-  end
-
-  if file_integrity_interval == 'monthly'
+  if file_integrity_tool != 'aide'
+    describe 'The system is not set to ' do
```
Comment (Amndeep7) [inline controls/SV-204445.rb:47]: not sure this is a typo with the incomplete describe statement (and no test to finish the sentence off)

File: controls/SV-204445.rb [hunk 36]
```diff
@@ -1,57 +1,56 @@
...
+      skip "The system is set to a `disconnected` state and you must validate
+        the state of the system packages manually, or through another process, if you
+        have an established update and patch process, please set this control as
+        `Not Applicable` with a `caevat` via an overlay."
+    end
+  elsif file_integrity_interval == 'monthly'
```
Comment (Amndeep7) [inline controls/SV-204445.rb:53]: "Chef InSpec will always evaluate all the tests contained within describe.one. It does not short-circuit upon evaluating a passing describe block."  however the tests displayed only have the one result listed in the case of the pass.  whereas in the case of the fail it lists out each fail.  if each describe is evaluated in the describe.one, shouldn't the correct behavior for the overarching pass be to mark any passing describe blocks as passed and any faileds as skips?  this is a question based outta my inspec ignorance and a feeling of uneasiness caused by the number of subtests being different for no apparent reason to me the end user.  like i had manually corrected only the one case there and it magically fixed the entire control i'd be pretty surprised lol.

image

**Review by Amndeep7 — CHANGES_REQUESTED** [review]

File: controls/SV-204445.rb (hunk 36 above)
Comment (em-c-rod) [reply controls/SV-204445.rb:53]: Yes, I saw this behavior in another control I was testing earlier with describe.one. For example, there was a control saying you must have either screen or tmux installed. If it fails, it states no screen installed and no tmux installed. If you install screen, it just says you pass because screen is installed and does not give you a failure that tmux is not installed because it only needs one of the checks to be true. Does that help this comment?

File: inspec.yml [hunk 37]
```diff
@@ -6,7 +6,7 @@ copyright_email: saf@groups.mitre.org
 license: Apache-2.0
 summary: "Inspec Validation Profile for Red Hat Enterprise Linux 7 STIG"
 version: 3.6.0
```
Comment (ejaronne) [inline inspec.yml:8]: should be 3.10.0

File: inspec.yml [hunk 38]
```diff
@@ -6,7 +6,7 @@ copyright_email: saf@groups.mitre.org
...
-inspec_version: ">= 4.0"
+inspec_version: ">= 4.26"
```
Comment (ejaronne) [inline inspec.yml:9]: Not sure why .26?

Comment (em-c-rod) [reply inspec.yml:9]: I remember that the file had two instances of the inspec_version in this file - one saying >= 4.0 and one saying  >= 4.26. I saw warnings saying something to the effect of "you defined this variable twice" and chose the more conservative of the two listed. I am looking at the [changelog from InSpec](https://raw.githubusercontent.com/inspec/inspec/main/CHANGELOG.md), but do not know the specific reason for 4.26.

File: controls/SV-204438.rb (hunk 32 above)
Comment (em-c-rod) [reply controls/SV-204438.rb:33]: I think this is an appropriate response because the file was not found and therefore the control is not going to give accurate results unless something is resolved to find the file, for example:
- setting the input('grub_user_boot_files') to the correct value if it is not the default for the system
- running the profile as root (--sudo) so the files are accessible

File: controls/SV-204458.rb [hunk 39]
```diff
@@ -17,31 +16,41 @@
...
+  tag cci: ['CCI-000366']
   tag nist: ['CM-6 b']
-  tag subsystems: ["redhat_release"]
-  tag 'host', 'container'
+  tag subsystems: ['redhat_release']
+  tag 'host'
+  tag 'container'
 
   release = os.release
+  supported_releases = ['7.6', '7.7', '7.9']
```
Comment (ejaronne) [inline controls/SV-204458.rb:33]: BUG: does not account for os.release that comes back as "7.9.2009". This passed in main, fails now.
image

**Comment by aaronlippold** [comment]
> Address the todo: https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/V3R10/libraries/matchers.rb#L3

This may not be needed anymore. We should validate that we actually need to have this in our profile.

File: controls/SV-204488.rb [hunk 40]
```diff
@@ -5,39 +5,41 @@
...
+  tag severity: 'medium'
+  tag gtitle: 'SRG-OS-000480-GPOS-00227'
+  tag gid: 'V-204488'
+  tag rid: 'SV-204488r861006_rule'
+  tag stig_id: 'RHEL-07-021040'
+  tag fix_id: 'F-4612r88657_fix'
+  tag cci: ['CCI-000318', 'CCI-000368', 'CCI-001812', 'CCI-001813', 'CCI-001814']
+  tag nist: ['CM-3 f', 'CM-6 c', 'CM-11 (2)', 'CM-5 (1)', 'CM-5 (1) (a)']
+  tag subsystems: ['init_files', 'home_dirs']
   tag 'host'
```
Comment (ejaronne) [inline controls/SV-204488.rb:36]: BUG: Introduced profile error while trying to do DELTA update:
image

File: controls/SV-204445.rb (hunk 36 above)
Comment (Amndeep7) [reply controls/SV-204445.rb:53]: What happens if you had both screen and tmux installed?  Does it only give the subtest result for the first one it attempted to assess or does it give the "extra credit" of the double pass?

Comment (em-c-rod) [reply controls/SV-204445.rb:53]: It gives one pass.

File: controls/SV-204610.rb [hunk 41]
```diff
@@ -1,51 +1,67 @@
...
+    describe 'Control not applicable - Kernel config must be done on the host' do
+      skip 'Control not applicable - Kernel config must be done on the host'
     end
   else
-    describe kernel_parameter('net.ipv4.conf.all.rp_filter') do
-      its('value') { should eq 1 }
+    rp_filter = 1
+    config_file_values = command('grep -r net.ipv4.conf.all.rp_filter /run/sysctl.d/* /etc/sysctl.d/* /usr/local/lib/sysctl.d/* /usr/lib/sysctl.d/* /lib/sysctl.d/* /etc/sysctl.conf 2> /dev/null').stdout.strip.split("\n")
+
+    describe 'net.ipv4.conf.all.rp_filter' do
```
[the remark this answers is not in the document]
Comment (em-c-rod) [reply controls/SV-204610.rb]: resolved here https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/pull/189/commits/f9d8c85b81cf56b1b9922156740b2f0a0b497fc3

File: controls/SV-204458.rb (hunk 39 above)
Comment (em-c-rod) [reply controls/SV-204458.rb]: I pushed a change for this. Feel free to test again when it is convenient for you.

File: controls/SV-204488.rb (hunk 40 above)
Comment (em-c-rod) [reply controls/SV-204488.rb:36]: I changed this control, but have not confirmed if it fixes the issue for you. Feel free to test when you have a chance.

**Comment by em-c-rod** [comment]
> > Address the todo: https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/V3R10/libraries/matchers.rb#L3
> 
> This may not be needed anymore. We should validate that we actually need to have this in our profile.

I made a separate issue for this to make it easier to address. https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/204

File: controls/SV-204458.rb (hunk 39 above)
Comment (ejaronne) [reply controls/SV-204458.rb]: Fixed Thanks!
image

File: controls/SV-204425.rb [hunk 42]
```diff
@@ -15,22 +14,22 @@
...
 
   if virtualization.system.eql?('docker') && !file('/etc/sysconfig/sshd').exist?
     impact 0.0
-    describe "Control not applicable - SSH is not installed within containerized RHEL" do
-      skip "Control not applicable - SSH is not installed within containerized RHEL"
+    describe 'Control not applicable - SSH is not installed within containerized RHEL' do
+      skip 'Control not applicable - SSH is not installed within containerized RHEL'
     end
   else
     describe sshd_config do
```
[the remark this answers is not in the document]
Comment (em-c-rod) [reply controls/SV-204425.rb]: Based on [this issue](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/165), this actually should pass if it is nil. I added a decribe.one to include that. @ejaronne if you want to take a look as well.

File: controls/SV-204445.rb (hunk 35 above)
Comment (em-c-rod) [reply controls/SV-204445.rb]: I updated to be consistent with another.

File: controls/SV-204444.rb (hunk 34 above)
Comment (em-c-rod) [reply controls/SV-204444.rb:59]: I added an issue to explore this.

File: controls/SV-204419.rb
[the remark this answers is not in the document]
Comment (em-c-rod) [reply controls/SV-204419.rb:1]: Created an [issue](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/206)

File: controls/SV-204429.rb
[the remark this answers is not in the document]
Comment (em-c-rod) [reply controls/SV-204429.rb:1]: https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/206

File: libraries/pam.rb
[the remark this answers is not in the document]
Comment (em-c-rod) [reply libraries/pam.rb:1]: https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/204

File: controls/SV-204415.rb (hunk 29 above)
Comment (em-c-rod) [reply controls/SV-204415.rb:39]: https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/204

File: controls/SV-204395.rb
[the remark this answers is not in the document]
Comment (em-c-rod) [reply controls/SV-204395.rb:1]: https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/205

File: controls/SV-204414.rb [hunk 43]
```diff
@@ -19,20 +18,20 @@
...
   tag nist: ['IA-5 (1) (b)']
-  tag subsystems: ["pwquality","password"]
-  tag 'host', 'container'
+  tag subsystems: ['pwquality', 'password']
+  tag 'host'
+  tag 'container'
 
   describe parse_config_file('/etc/security/pwquality.conf') do
-    its('maxclassrepeat') { should cmp input('classrepeat') }
     its('maxclassrepeat') { should_not cmp > input('max_classrepeat') }
```
[the remark this answers is not in the document]
Comment (em-c-rod) [reply controls/SV-204414.rb:35]: Resolved.

[the remark this answers is not in the document]
Comment (em-c-rod) [reply controls/SV-204414.rb:35]: Resolved.

File: libraries/pam.rb
Comment (em-c-rod) [reply libraries/pam.rb:1]: https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/204

File: controls/SV-204407.rb
[the remark this answers is not in the document]
Comment (em-c-rod) [reply controls/SV-204407.rb:1]: https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/205

[the remark this answers is not in the document]
Comment (em-c-rod) [reply controls/SV-204407.rb:1]: Fixed here and in a few other controls. This is an issue when there is a cmp >, <, >=, <= with a nil or empty input for comparison. There may be more controls like this to add a nil check to in future development.

File: controls/SV-204440.rb (hunk 33 above)
Comment (karikarshivani) [reply controls/SV-204440.rb:33]: Historically, AWS support has been a separate effort because we have to consider a lot of different ways of testing the same STIG rule (for SV-204438 and SV-204440, it could be checking parameter values, AWS EC2-specific file paths, etc). For now, I've updated @em-c-rod's [issue](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/206) to include this AWS support suggestion. Thanks @Amndeep7

File: controls/SV-204405.rb
[the remark this answers is not in the document]
Comment (karikarshivani) [reply controls/SV-204405.rb:1]: Makes sense to me! Logged it https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/207

File: controls/SV-204427.rb [hunk 44]
```diff
@@ -73,55 +73,55 @@
   alt = input('alternate_rules')
 
   describe.one do
```
[the remark this answers is not in the document]
Comment (karikarshivani) [reply controls/SV-204427.rb:75]: Logged it https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/issues/207
